name: wct-tf
channels:
  - defaults
dependencies:
  - h5py>=2.7,<3
  - hdf5>=1.8,<2
  - mkl>=2018,<2019
  - pip>=9.0.1,<=19
  - python=3.6.6
  - scikit-image=0.13.1
  - pip:
    - black
    - Keras==2.0.9
    - tensorflow-gpu==1.2.1
